id: I2FF73100
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:10:07.945782
last_modified: 2023-02-08 15:10:07.945934
source_metadata:
  title: Laṅkāvatārasūtra
  language: sa
bases:
  63F0:
    base_file: 63F0.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
